### ISSUE TITLE
[ROX-15068] Enable modern Falco probe engine

### ISSUE THREAD

**Issue by erthalion** [stackrox/collector#1008]
The idea is to make "modern" Falco probe engine available for Collector. To achieve that:

- [x] Syncing up our Falco fork with the latest changes #1016
- [x] Update Collector probe loader to recognize and load new type of probes #1065 
- [x] Modern Falco probes supports only relatively new kernel versions (>= 5.8), the lower boundary is enforced via version checking. Figure out if it's possible to bump it down for lower versions where necessary features were backported #1037 
- [x] Customize modern Falco probes to load only a certain subset of tail-called programs to avoid unsupported syscalls problems #1044 
- [x] Make sure sinsp-example could be used for testing, and specify few tests for the new probe in isolation (optionally) #1043 
- [ ] Implement standalone Collector for testing, and specify few tests for the new probe with Collector only (optionally)

See ROX-15068 for the higher-level details.
