### ISSUE TITLE
[ROX-15069] Collector support of BTF probes

### ISSUE THREAD

**Issue by erthalion** [stackrox/collector#1011]
The idea is to teach Collector to use "modern" Falco probe engine in a backward compatible way. To achieve that:

- [x] Implement new way of loading probes located inside the image. #1017 
- [x] Implement heuristics for Collector to find out if BTF is supported. In the simplest scenario it could be a kernel version check, but ideally more elaborated feature verification is needed (in case of backported functionality). #1018 
- [x] Implement fallback mechanism, to let Collector switch back to regular probes if it fails to load the new one. The definition of "failed to load" means simply an error from kernel, but in theory could be extended to more runtime validation that everything is in place. #1066 
- [ ] Display failed BTF load via Collector status, similar to cases when no probes could be loaded. #1077 
- [ ] (Optional for MVP) Implement new way of getting probes via searching in the container itself, since BTF aware probes are going to be embedded into the container. This has to be implemented flexible though, as there still could be cases when it's beneficial to load even BTF aware probe, and the original probes have to be loaded as usual anyway.
- [ ] (Optional for MVP) Try to refactor the loading logic to make it more flexible, having in mind potentially delegating probe loading into the kernel to other components.

See ROX-15069 for the higher-level details.
