### ISSUE TITLE
[ROX-15070] BTF infrastructure

### ISSUE THREAD

**Issue by erthalion** [stackrox/collector#1014]
The idea is to make CI pipelines support the "modern" probes. To achieve that:

- [x] Build Falco with modern bpf enabled #1068
- [x] Create a new testing pipeline for "modern" probes #1067 
- [ ] (Optional for MVP) Modify the build pipeline to create and embed the new probe into an image #1019 
- [ ] (Optional for MVP) To make solution more robust, include new probe into the regular probe delivery channels as well (so that Collector can try to fetch those probes via some alternative way)
- [ ] (Optional for MVP) Investigate possibility of using btfhub
 
See ROX-15070 for the higher-level details.
